GET http://localhost:5001/sw25datas/us-central1/getDatas

###
POST http://localhost:5001/sw25datas/us-central1/postData
content-type: application/json

{
    "Status": {"reac": "てスト","mind": "3","imp": "0","life": "4","int": "命令を聞く","speed": "15 / -","weak": "物理ダメージ+2点","pop": "5","habi": ["不明"],"perc": "魔法","preem": "8","weakValue": "11","lang": ["なし"]},
    "Top": {"race": "魔法生物","name": "テストデータ","lv": "2"},
    "Parts": [{"damage": "4","hit": "4","mp": "","name": "腕","hp": "18","avoid": "3", "protect": "1"}],
    "Abilitys": [],
    "Explanation": "テストモンスター",
    "tag": ["main"],
    "Bootys": [{"item": "なし","dice": "2～8"}]
  }


###
GET http://127.0.0.1:5001/sw25datas/us-centrall/createBundle
content-type: application/json

###
GET https://us-central1-sw25datas.cloudfunctions.net/createBundle